//interface
import { PlantStatus, TaskItemProps } from "@interface/DataProps/TaskItemProps";
export const dummyTaskItem: TaskItemProps[] = [
  {
    taskId: "task1",
    plantId: "plant1",
    contId: "cont2",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-08-26"),
    status: PlantStatus.Grow,
    farmerName: "Blanco",
  },
  {
    taskId: "task2",
    plantId: "plant2",
    contId: "cont1",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-08-28"),
    status: PlantStatus.Harvest,
    farmerName: "Blanco",
  },
  {
    taskId: "task3",
    plantId: "plant2",
    contId: "cont3",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-10"),
    status: PlantStatus.Grow,
    farmerName: "Duran",
  },
  {
    taskId: "task4",
    plantId: "plant1",
    contId: "cont2",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-13"),
    status: PlantStatus.Grow,
    farmerName: "Mendoza",
  },
  {
    taskId: "task5",
    plantId: "plant2",
    contId: "cont1",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-19"),
    status: PlantStatus.Harvest,
    farmerName: "Duran",
  },
  {
    taskId: "task6",
    plantId: "plant3",
    contId: "cont3",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-19"),
    status: PlantStatus.Grow,
    farmerName: "Mendoza",
  },
  {
    taskId: "task7",
    plantId: "plant1",
    contId: "cont1",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-20"),
    status: PlantStatus.Harvest,
    farmerName: "Duran",
  },
  {
    taskId: "task8",
    plantId: "plant2",
    contId: "cont1",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-20"),
    status: PlantStatus.Grow,
    farmerName: "Mendoza",
  },
  {
    taskId: "task9",
    plantId: "plant2",
    contId: "cont1",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-08-07"),
    status: PlantStatus.Harvest,
    farmerName: "Duran",
  },
  {
    taskId: "task11",
    plantId: "plant2",
    contId: "cont1",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-08-07"),
    status: PlantStatus.Harvest,
    farmerName: "Duran",
  },
  {
    taskId: "task10",
    plantId: "plant3",
    contId: "cont3",
    datePlanted: new Date("2023-08-01"),
    dateExpectedHarvest: new Date("2023-09-10"),
    status: PlantStatus.Grow,
    farmerName: "Mendoza",
  },
];
