export enum COLORS {
    BACKGROUNDCOLORSECONDARY = "#BCEB3C",
    BACKGROUNDCOLOR = "#36922e",
    BACKGROUNDGRADIENTSTART = "#3eb14b",
    BACKGROUNDGRADIENTEND = "#67ff78",
    BACKGROUNDGOODVALUE = "#67ff78",
    BACKGROUNDCRITICALVALUE = "#f89f9f",
  }